[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "ExAzZQ8rEFwiTHybeRwMGzGiheMm4TtsNwy5KwwH4cqd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"  
program = "tests/core.so"
